name: Build APK
on:
  - page_build
  - workflow_dispatch

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

jobs:
    build-apk:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: PWA to APK
          uses: ./.github/bubblewrap_action
          with:
            project-root-folder: 'bubblewrap'
        - name: Draft Release
          uses: softprops/action-gh-release@v2
          with:
            # note you'll typically need to create a personal access token
            # with permissions to create releases in the other repo
            draft: true
            files: 'bubblewrap/*.apk'

